apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "secure-app-platform.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secure-app-platform.labels" . | nindent 4 }}
data:
  # Application configuration
  app.yaml: |
    database:
      host: {{ .Values.config.app.database.host | quote }}
      port: {{ .Values.config.app.database.port }}
      name: {{ .Values.config.app.database.name | quote }}
    
    cache:
      enabled: {{ .Values.config.app.cache.enabled }}
      type: {{ .Values.config.app.cache.type | quote }}
      {{- if .Values.redis.enabled }}
      redis:
        host: {{ include "secure-app-platform.redis.fullname" . }}
        port: 6379
        {{- if .Values.redis.auth.enabled }}
        auth: true
        {{- end }}
      {{- end }}

