apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secure-app-platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secure-app-platform.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "secure-app-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "secure-app-platform.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
          {{- include "secure-app-platform.env" . | nindent 10 }}
          {{- if and .Values.auth.enabled }}
          - name: CUSTOM_USERS_JSON
            value: |
              {{- toJson .Values.auth.users.list | nindent 14 }}
          {{- end }}
          {{- include "secure-app-platform.resources" . | nindent 10 }}
          volumeMounts:
            {{- include "secure-app-platform.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "secure-app-platform.volumes" . | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
